### ISSUE TITLE
Question to difference in Pythonv vs Java/TypeScript/C# of TennisGame3

### ISSUE THREAD

**Issue by StephanSvoboda** [emilybache/Tennis-Refactoring-Kata#118]
First of all thanks for the great collection of Katas

In TennisGame3 `WonPoint(playerName)` all languages I checked implement it like this:
```
WonPoint(playerName)
    if playerName == "player1"
```
So if in "production" we want to know the score of Nadal vs Djokovic Nadal will never score a point or better said each point Nadal scores is counted for Djokovic.

In Python it is different:
`if n == self.p1N`

Is this difference intentional? Maybe to provoke the question if bugs should be fixed while refactoring.

**Comment by emilybache** [comment]
Hi, 
Glad you like that katas.

No it's not intentional, it's a translation error in the python version. I want there to be a bug with the player names as you indicate. It is important not to fix bugs while refactoring, unless you've agreed it with your users.

Emily

**Comment by StephanSvoboda** [comment]
I hope you will than accept my pull request to introduce a bug. (This feels wrong)
