### ISSUE TITLE
Introductory text is not helpful

### ISSUE THREAD

**Issue by koeckera** [emilybache/Tennis-Refactoring-Kata#14]
The introductory text suggests that refactoring is just a means to spend some billable hours on a project. That paints a dangerously wrong picture to some people. Wouldn't it suffice to say that e.g. "you" have been tasked with adding a new feature to the program and decided to clean up first?

**Comment by emilybache** [comment]
Hi,
I think if you do the exercise and still think afterwards that refactoring is simply a means to spend some billable hours on a project, then you've totally missed the point of the exercise.

**Comment by koeckera** [comment]
I wholeheartedly agree.

The reason I bring this up is that a colleague of mine tried to incorporate this very helpful Kata in our processes. He faced a lot of criticism not because of the exercise itself but because people didn't read past the introduction.

**Comment by emilybache** [comment]
I tweaked the README a little, I hope it's now clear that there may be more reasons for doing refactoring than just billing more hours, and that those reasons might become apparent by doing the exercise.
