### ISSUE TITLE
The cyber-dojo links do not work...

### ISSUE THREAD

**Issue by jorgearanda** [emilybache/Tennis-Refactoring-Kata#15]
...or, rather, they take the user to a page offering them to buy the domain name.

**Comment by emilybache** [comment]
Sorry about that. I will fix them...

**Comment by jorgearanda** [comment]
Thanks! And by the way, I loved the Coding Dojo handbook.

**Comment by paulroho** [comment]
I think this issue can be closed.

**Comment by jorgearanda** [comment]
The cyber-dojo page is still just an offer to buy the domain name.

**Comment by paulroho** [comment]
Maybe we should be more concrete: The links at the bottom of Readme.md work fine for me. Which links do not work?

**Comment by jorgearanda** [comment]
Ah! This is true --- I was going with the old cyber-dojo.com links. Apologies!
