### ISSUE TITLE
C#: Improve the out-of-the-box-experience

### ISSUE THREAD

**Issue by paulroho** [emilybache/Tennis-Refactoring-Kata#23]
For people not used to using NUnit, the following things would be of great help:

* Provide a solution file
* Change csproj to a ClassLibrary project, remove then obsolete Main.cs
* Add nuget package for NUnit
* Provide a hint how to install the NUnit VsTestAdapter

I will send a pull request.

**Comment by emilybache** [comment]
Thankyou for the pull request that fixes these issues
