### ISSUE TITLE
Broken link to this kata from your site

### ISSUE THREAD

**Issue by gsaslis** [emilybache/Tennis-Refactoring-Kata#29]
Hi there, 

Just a quick one: 
The link from the article on http://coding-is-like-cooking.info/category/code-kata/ to this page is broken. 
I am referring to the code in the text "You can get the starting code here.", which points to https://github.com/emilybache/Refactoring-Katas, but rather should point to https://github.com/emilybache/Tennis-Refactoring-Kata/ 

Cheers, 
Yorgos

P.S: Thanks for sharing all this!  :  )

**Comment by emilybache** [comment]
Thankyou! I've hopefully fixed the link now

Emily
