### ISSUE TITLE
Sugerencia para code smell Switch Case

### ISSUE THREAD

**Issue by KellyVaque** [emilybache/Tennis-Refactoring-Kata#53]
Hola, revise tu proyecto y hay cosas que podrías cambiar para facilitar el entendimiento del mismo.
En tu clase TennisGame1 tienes una sentencia switch case en el método getScore(), la cual no esta mal pero sin embargo "daña" tu código visualmente por lo que te recomiendo refactorizar este método.

Técnica de refactorización: Para este tipo de code smell te recomiendo extraer esta sentencia en un nuevo método y con el fin de deshacerte del switch-case puedes usar enum, para encapsular los casos del switch.

**Comment by emilybache** [comment]
My Spanish is not great but I think you're making a comment about the exercise. I'm glad you're enjoying having a go at it.
