### ISSUE TITLE
Sugerencia code Smell Primitive Obsession

### ISSUE THREAD

**Issue by KellyVaque** [emilybache/Tennis-Refactoring-Kata#54]
Hola, revisando tu código detalladamente he detectado un code smell bastante común, primitive obsession este code smell se debe a que usas string para crear los jugadores lo cual complica un poco añadir nuevas funcionalidades al programa.

Técnica de Refactorización: Te recomiendo refactorizar este code smell usando clases en lugar de datos primitivos, podrías crear una clase Player que guarde los datos basicos del jugador y una clase PlayerGameDetails que guarde los datos del jugador referente al juego como su puntaje.

Espero te sirva de ayuda.

**Comment by emilybache** [comment]
My Spanish is not great but I think you're making a comment about the exercise. I'm glad you're enjoying having a go at it.
