### ISSUE TITLE
Sugerencia code smell Speculative Generality

### ISSUE THREAD

**Issue by KellyVaque** [emilybache/Tennis-Refactoring-Kata#55]
Hola, he leido tu código y he encontrado lineas de código en la clase TennisGame2 que no tienen ningún uso ni aportan funcionalidad a tu programa, por lo que te recomendaría usar una técnica de refactorización para solucionar esto.

Técnica de refactorización: Te recomiendo que elimines esta parte de tu código y la pongas cuando realmente vayas a usarla para que no compliques el entendimiento del mismo

Ojala te sirva de ayuda.

**Comment by emilybache** [comment]
My Spanish is not great but I think you're making a comment about the exercise. I'm glad you're enjoying having a go at it.
