### ISSUE TITLE
CS Tests dont run

### ISSUE THREAD

**Issue by H-clewer** [emilybache/Tennis-Refactoring-Kata#77]
I cloned the repo. Try to run the CSharp tests but an error occurs: 

"No test is available in D:\*\*\Tennis-Refactoring-Kata\csharp\Tennis\bin\Debug\net5.0\Tennis.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again"

I'm not sure how to fix this.

**Comment by emilybache** [comment]
I'm really not sure how to fix that either. If you look in the repository there are no references to that particular path on disk. I'm not great with .net myself, but I suspect this project just uses an older version of the .net platform and framework than your IDE is expecting.

I wonder if you've tried creating a new empty project and just copying and pasting the relevant classes and tests into it? There are only a few of them.

**Comment by Hazzamanic** [comment]
It is missing an adapter to run the tests, I've opened a pr (#79) adding the vs runner, which supports `dotnet test`, visual studio and visual studio code test runners.

**Comment by emilybache** [comment]
Thankyou for the issue and the fix!
